name: Build and deploy
on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: main
          build_dir: html  # Change to your subdirectory name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
